name: Test pip install requirements

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        platform: [macos-14]
        python-version: ["3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install torch
        run: python -m pip install torch==2.3.1 torchvision torchaudio
      - name: Install xformers
        if: matrix.platform == 'macos-14'
        run: |
          python -m pip install https://github.com/rsxdalv/xformers/releases/download/v0.0.27/xformers-0.0.27+184b280.d20241026-cp310-cp310-macosx_11_0_universal2.whl
      - name: Install pytest
        run: python -m pip install pytest
      - name: Test attention mask
        run: pytest tests/test_attention_mask.py
      - name: Test Attention Patterns
        run: pytest tests/test_attention_patterns.py
      - name: Test Attentions
        run: pytest tests/test_attentions.py
      - name: Test rotary embeddings
        run: pytest tests/test_rotary_embeddings.py